[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "jiminy-cricket-tools"
version = "0.1.0"
description = "Runtime conscience helpers with configurable safety checks."
readme = "README.md"
authors = [{ name = "Agentic Ritual Engine" }]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = []

[project.urls]
Homepage = "https://example.com/agentic-ritual-engine"

[tool.setuptools.packages.find]
where = ["."]
